version: 1.3.2

model: "Early"

defaults:
  - _self_
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: grid

hydra:
  sweeper:
    direction: ["minimize"]
    study_name: Glaucoma Detection
    storage: null
    n_trials: 3
    n_jobs: 1

    params:
      model: choice("U-Net", "FCDense", "Early")